KalahariCollarV17/Models/Pet.cs
using KalahariCollarV17.Areas.Identity.Data;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace KalahariCollarV17.Models
{
    public enum Type
    {
        Dog, Cat
    }
    public class Pet
    {
        public int Id { get; set; }

        public Int64 TrackerID {  get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public Type? Type { get; set; } // Add the type property (e.g., "cat" or "dog")
                                        // Add other pet properties
        public string Breed { get; set; }
        public string OwnerId { get; set; }
        public string Location { get; set; } // Add the location property
                                             // Add other pet properties

        public ApplicationUser Owner { get; set; }
    }
}

KalahariCollarV17/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KalahariCollarV17.Data;
using KalahariCollarV17.Models;
using KalahariCollarV17.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using PagedList;
using System.Security.Claims;
using System.Drawing;
using Microsoft.AspNetCore.Hosting.Builder;
using Microsoft.Data.SqlClient;

namespace KalahariCollarV17.Controllers
{
    [Authorize]
    public class PetsController : Controller
    {
        private readonly PetContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<PetsController> _logger;
        //string UserId;
        public PetsController(PetContext context, UserManager<ApplicationUser> userManager, ILogger<PetsController> logger)
        {
            _context = context;
            _userManager = userManager;
            //UserId = User.FindFirstValue(ClaimTypes.Email);
            _context = context;
            _logger = logger;
        }

        // GET: Pets
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var pets = from p in _context.Pets
                       select p;
            if (!String.IsNullOrEmpty(searchString))
            {
                pets = pets.Where(p => p.Name.Contains(searchString));
            }
            Console.WriteLine(_context.Database.GetConnectionString());
            var petsFromDatabase = _context.Pets.Where(p => p.OwnerId.Equals(_userManager.GetUserId(User))).ToList();

            // Map the data to the view model
            var petViewModels = petsFromDatabase.Select(p => new Pet
            {
                Id = p.Id,
                Name = p.Name,
                Type = p.Type,
                Breed = p.Breed,
                Location = p.Location,
                TrackerID = p.TrackerID,
                Age = p.Age,
                // Map other properties
            }).ToList();


            switch (sortOrder)
            {
                case "name_desc":
                    pets = pets.OrderByDescending(p => p.Name);
                    break;
                default:
                    pets = pets.OrderBy(p => p.Name);
                    break;
            }
            // var petContext = _context.Pet.Include(p => p.Owner);
            //  return View(await petContext.ToListAsync());
            // Pass the view model collection to the view
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(petViewModels.ToPagedList(pageNumber, pageSize));

        }

        // GET: Pets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pets == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
                //.Include(p => p.OwnerId)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // GET: Pets/Create
        public IActionResult Create()
        {
            ViewData["OwnerId"] = _userManager.GetUserId(User);
            return View();
        }

        // POST: Pets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TrackerID,Name,Age,Type,Breed,OwnerId,Location")] Pet pet)
        {
            if (pet.Age > 0)
            {
                if (pet.TrackerID > 100000000000000 && pet.TrackerID < 999999999999999)
                {
                    Console.WriteLine(pet.Name);
                    if (!pet.Name.Equals("") && !pet.Type.Equals("") && !pet.Breed.Equals("") && !pet.Location.Equals("") && !pet.TrackerID.Equals("") && !pet.Age.Equals(""))
                    {
                        pet.OwnerId = _userManager.GetUserId(User); ;
                        Console.WriteLine(pet.OwnerId);
                        _context.Add(pet);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }


                    else
                    {
                        // Log ModelState errors
                        foreach (var modelState in ModelState.Values)
                        {
                            foreach (var error in modelState.Errors)
                            {
                                Console.WriteLine(error.ErrorMessage);
                            }
                        }
                    }
                    ViewData["OwnerId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", pet.OwnerId);
                }
                else
                {
                    ModelState.AddModelError("TrackerID", "Tracker ID is the tracking device's IMEI number and should be 15 digits long, never starting with 0");
                }
            }
            else
            {
                ModelState.AddModelError("Age", "Age Cannot be Less than 0");
            }
            return View(pet);

        }

        // GET: Pets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pets == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets.FindAsync(id);
            if (pet == null)
            {
                return NotFound();
            }
          //  ViewData["OwnerId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", pet.OwnerId);
            return View(pet);
        }

        // POST: Pets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TrackerID,Name,Age,Type,Breed,Location")] Pet pet)
        {
            if (pet.Age > 0)
            {
                if (pet.TrackerID > 100000000000000 && pet.TrackerID < 999999999999999)
                {
                    Console.WriteLine(pet.Name);
                    if (!pet.Name.Equals("") && !pet.Type.Equals("") && !pet.Breed.Equals("") && !pet.Location.Equals("") && !pet.TrackerID.Equals("") && !pet.Age.Equals(""))
                    {
                        pet.OwnerId = _userManager.GetUserId(User); 
                        Console.WriteLine(pet.OwnerId);
                        _context.Update(pet);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }


                    else
                    {
                        // Log ModelState errors
                        foreach (var modelState in ModelState.Values)
                        {
                            foreach (var error in modelState.Errors)
                            {
                                Console.WriteLine(error.ErrorMessage);
                            }
                        }
                    }
                    ViewData["OwnerId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", pet.OwnerId);
                }
                else
                {
                    ModelState.AddModelError("TrackerID", "Tracker ID is the tracking device's IMEI number and should be 15 digits long, never starting with 0");
                }
            }
            else
            {
                ModelState.AddModelError("Age", "Age Cannot be Less than 0");
            }
            return View(pet);

           /* Console.WriteLine(pet.Name);
            if (id != pet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PetExists(pet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
        //    ViewData["OwnerId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", pet.OwnerId);
            return View(pet);
           */
        }

        // GET: Pets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pets == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
               // .Include(p => p.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // POST: Pets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

KalahariCollarV17/Views/Pets/Create.cshtml
@model KalahariCollarV17.Models.Pet

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>
<head>
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KalahariCollar.styles.css" asp-append-version="true" />
</head>
<h4>Pet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" onsubmit="myButton.disabled = true; return true;" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="TrackerID" class="control-label"></label>
                <input asp-for="TrackerID" class="form-control" />
                <span asp-validation-for="TrackerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Type:</label>
                <select asp-for="Type" class=" form-control">
                    <option value=""> Please select</option>
                    <option value="Dog"> Dog </option>
                    <option value="Cat"> Cat </option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Breed" class="control-label"></label>
                <input asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class ="form-control" asp-items="ViewBag.OwnerId"></select>
            </div>
            *@
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" name="myButton" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KalahariCollarV17/Views/Pets/Delete.cshtml
@model KalahariCollarV17.Models.Pet

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>
<body class="mainbody">
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrackerID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrackerID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Breed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Breed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        @*
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.Id)
        </dd>
        *@
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-primary" asp-action="Index">Back to List</a>
    </form>
</div>
    </body>

KalahariCollarV17/Views/Pets/Details.cshtml
@model KalahariCollarV17.Models.Pet

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KalahariCollar.styles.css" asp-append-version="true" />
</head>
<h1>Pet Profile</h1>
<body class="mainbody">
<div>
    <h4>Pet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrackerID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrackerID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Breed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Breed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        @*
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Owner.Id)
        </dd>
        *@
    </dl>
</div>
<div>
    <a  class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

    </body>

KalahariCollarV17/Views/Pets/Edit.cshtml
@model KalahariCollarV17.Models.Pet

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KalahariCollar.styles.css" asp-append-version="true" />
</head>
<h1>Edit</h1>
<body class="mainbody">
<h4>Pet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" onsubmit="myButton.disabled = true; return true;" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" /> 
            <div class="form-group">
                <label asp-for="TrackerID" class="control-label"></label>
                <input asp-for="TrackerID" class="form-control" />
                <span asp-validation-for="TrackerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Breed" class="control-label"></label>
                <input asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
            @*
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            *@
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" name="myButton"  />
                   | <a class="btn btn-primary" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KalahariCollarV17/Views/Pets/Index.cshtml
@model PagedList.IPagedList<KalahariCollarV17.Models.Pet>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KalahariCollar.styles.css" asp-append-version="true" />
</head>
<h1>Your Pets</h1>

<body class="mainbody">
<p>
    <a class="btn btn-primary" asp-action="Create">Add New Pet</a>
</p>

    
    
<div class="card-columns">
@foreach (var item in Model)
{
           
    <div class="card">
        <div class="row">
            <h1>@item.Name</h1>
            <div class="buttons-col">
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="Pets" asp-action="Details" asp-route-id="@item.Id">Profile</a>
                    </li>
                    <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="Pets" asp-action="Edit" asp-route-id="@item.Id">Edit </a>
                    </li>
                    <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="Pets" asp-action="Location" asp-route-id="@item.Id">Track</a>
                    </li>
                    <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="Pets" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </li>
                </ul>
            </div>
            <div class="track-col">
            </div>
        </div>
    </div>
}
      
    </div>
</body>

@*
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TrackerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Breed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Owner)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TrackerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Breed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
*@

KalahariCollarV17/Views/Pets/Location.cshtml
@model KalahariCollarV17.Models.Pet

@{
    ViewData["Title"] = "Location";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KalahariCollar.styles.css" asp-append-version="true" />
  <title>Google Maps Example</title>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCERnEroIlqCPoAep7baOEjacpPAVitU0I"></script>
  <style>
    #map {
      height: 600px; /* Adjust the height to make the map longer */
    }
  </style>
</head>
<body class="mainbody">
  <div id="map" style="height: 600px;"></div>
    <a class ="btn btn-primary" id="start-tracking">Start Tracking </a>
    <a class="btn btn-primary" id="stop-tracking">Stop Tracking</a>
  <script>
        let poly;
            let map;
        let watchId; // To store the ID of the geolocation watch

      function initMap() {
          map = new google.maps.Map(document.getElementById("map"), {
              center: { lat: -22.559722, lng: 17.083611 }, // Centered on Namibia
              zoom: 6,
          });
          const triangleCoords = [
              { lat: -22.3839, lng: 20.1137 },
              { lat: -24.0717, lng: 17.5831 },
              { lat: -24.2889, lng: 15.2605 },
              { lat: -24.8598, lng: 18.8046 },
          ];

          // Construct the polygon.
          const bermudaTriangle = new google.maps.Polygon({
              paths: triangleCoords,
              strokeColor: "#FF0000",
              strokeOpacity: 0.8,
              strokeWeight: 2,
              fillColor: "#FF0000",
              fillOpacity: 0.35,
                triangleCoords: triangleCoords,
                editable: true

          });

          bermudaTriangle.setMap(map);

           
      }

        // Handles click events on a map, and adds a new point to the Polyline.
        

        function startTracking() {
            if (navigator.geolocation) {
                watchId = navigator.geolocation.watchPosition(
                    (position) => {
                        const pos = {
                            lat: position.coords.latitude,
                            lng: position.coords.longitude,
                        };
                        map.setCenter(pos);
                        new google.maps.Marker({
                            position: pos,
                            map: map,
                            title: "Your Location",
                        });
                    },
                    () => {
                        alert("Error: The Geolocation service failed.");
                    }
                );
            } else {
                alert("Error: Your browser doesn't support geolocation.");
            }
        }

        function stopTracking() {
            if (navigator.geolocation && watchId) {
                navigator.geolocation.clearWatch(watchId);
            }
        }

        document.getElementById("start-tracking").addEventListener("click", startTracking);
        document.getElementById("stop-tracking").addEventListener("click", stopTracking);

        initMap();
    
  </script>
</body>
</html>